[package]
name = "ic-wasi-polyfill"
version = "0.3.11"
edition = "2021"


[dependencies]
ic-cdk = "0.8"
ic-stable-structures = "0.5.4"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", rev = "600be4d7fd3b7335d504623c43e4da030bf424c2" }
rand = "0.8.5"
function_name = "0.3.0"

[features]
transient=[]
report_wasi_calls=[]
skip_unimplemented_functions=[]


[lib]
crate-type = ["staticlib","lib"]
