[package]
name = "ic-wasi-polyfill"
version = "0.3.9"
edition = "2021"


[dependencies]
ic-cdk = "0.8"
ic-stable-structures = "0.5.4"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", rev = "98a42fa9a32e999d5c2eb7ea2852bb1c62cff402" }
rand = "0.8.5"
function_name = "0.3.0"

[features]
transient=[]
report_wasi_calls=[]
skip_unimplemented_functions=[]


[lib]
crate-type = ["staticlib","lib"]
