[package]
name = "ic_polyfill"
version = "0.1.0"
authors = ["Stanislav Golubtsov <sgaflv@gmail.com>"]
edition = "2021"


[dependencies]
ic-cdk = "0.7.3"

[build]
target = "wasm32-wasi"

[lib]
crate-type = ["staticlib"]