[package]
name = "ic-wasi-polyfill"
version = "0.3.7"
authors = ["Stanislav Golubtsov"]
edition = "2021"


[dependencies]
ic-cdk = "0.8.0"
ic-stable-structures = "0.5.3"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", version = "0.1.8" }
rand = "0.8.5"

[build]
target = "wasm32-wasi"

[lib]
crate-type = ["staticlib","lib"]
