[package]
name = "ic-wasi-polyfill"
version = "0.3.14"
edition = "2021"
keywords = ["ic", "wasi-polyfill"]
description = "The project provides polyfill implementation of *wasi_unstable* and *wasi_snapshot_preview1* functions using IC System API."
license = "MIT"

[dependencies]
ic-cdk = "0.12.1"
ic-stable-structures = "0.6.2"
stable-fs = "0.1.11"


rand = "0.8.5"
function_name = "0.3.0"

[features]
transient=[]
report_wasi_calls=[]
skip_unimplemented_functions=[]


[lib]
crate-type = ["staticlib","lib"]
