[package]
name = "ic-wasi-polyfill"
version = "0.3.8"
edition = "2021"


[dependencies]
ic-cdk = "0.8.1"
ic-stable-structures = "0.5.4"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", rev = "77575a3f3b19a7decd5258f9d3ab44782bb597ae" }
rand = "0.8.5"
function_name = "0.3.0"

[features]
transient=[]

[build]
target = "wasm32-wasi"

[lib]
crate-type = ["staticlib","lib"]
