[package]
name = "ic-wasi-polyfill"
version = "0.3.9"
edition = "2021"


[dependencies]
ic-cdk = "=0.8.0"
ic-stable-structures = "0.5.4"
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", rev = "3c65a53300b566c129d62fafe6aa39e953381f6e" }
rand = "0.8.5"
function_name = "0.3.0"

[features]
transient=[]
report_wasi_calls=[]


[lib]
crate-type = ["staticlib","lib"]
